apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deploy
  labels:
    apps: hello-world
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: kshun1207/mytomcat:14
        ports:
        - containerPort: 8080
